Новостной портал/news/news/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('news/', include('news_bd.urls')),
    path("accounts/", include("allauth.urls")),
    path('swagger-ui/', TemplateView.as_view(
       template_name='swagger-ui.html',
       extra_context={'schema_url':'openapi-schema'}
   ), name='swagger-ui')
]

Новостной портал/news/news_bd/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.core.cache import cache # импортируем наш кэш
# Create your models here.

class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_rating = models.FloatField(default=0.0)
    def update_rating(self):
        post_rating = 0.0
        comments_rating = 0.0
        posts_comments_rating = 0.0

        posts = Post.objects.filter(author= self)
        for p in posts:
            post_rating += p.post_rating

        comments = Comment.objects.filter(user=self.user)

        for c in comments:
            comments_rating += c.comment_rating

        posts_comments = Comment.objects.filter(post__author = self)

        for pc in posts_comments:
            posts_comments_rating += pc.comment_rating

        self.user_rating = post_rating * 3 + comments_rating + posts_comments_rating
        self.save()
    def __str__(self):
        return f'{self.user}'


class Category(models.Model):
    category_name = models.CharField(max_length=100, unique=True)
    subscribers = models.ManyToManyField(User, related_name='categories')

    def __str__(self):
        return self.category_name

class Post(models.Model):
    Article = 'AR'
    News = 'NE'
    types = [(Article,'Статья'),(News,'Новость')]

    author = models.ForeignKey(Author, on_delete = models.CASCADE)
    type_post = models.CharField(max_length=2, choices=types, default=News)
    time_post = models.DateTimeField(auto_now_add = True)
    category = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=100)
    text = models.TextField()
    post_rating = models.FloatField(default=0.0)

    def like(self):
        self.post_rating= self.post_rating + 1.0
        self.save()
    def dislike(self):
        self.post_rating = self.post_rating - 1.0
        self.save()
    def preview(self):
        self.post_preview = self.text[:124] + '...'
        return self.post_preview
    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)  # сначала вызываем метод родителя, чтобы объект сохранился
        cache.delete(f'post-{self.pk}')  # затем удаляем его из кэша, чтобы сбросить его
    def __str__(self):
        return self.title


class PostCategory(models.Model):
    post_id = models.ForeignKey(Post, on_delete = models.CASCADE)
    category_id = models.ForeignKey(Category, on_delete = models.CASCADE)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete = models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    time_comment = models.DateTimeField(auto_now_add=True)
    comment_rating = models.FloatField(default=0.0)

    def like(self):
        self.comment_rating = self.comment_rating + 1.0
        self.save()
    def dislike(self):
        self.comment_rating = self.comment_rating - 1.0
        self.save()
    def __str__(self):
        return self.text

Новостной портал/news/templates/article_create.html
{% extends 'flatpages/default.html' %}
{% load i18n %}
{% block content %}
<br>
<h1>{% trans 'Статья' %}</h1>
<br>
<form action="{% url 'set_language' %}" method="POST"> 
		{% csrf_token %} <!-- Не забываем по csrf_token для POST запросов -->
        <input type="hidden" name="next" value="{{ redirect_to }}">
        <select name="language" id="">
            {% get_available_languages as LANGUAGES %} <!-- получаем языки -->
            {% get_language_info_list for LANGUAGES as languages %} <!-- Помещаем их в список languages -->
            {% get_current_language as LANGUAGE_CODE %}
            {% for language in languages %} <!-- Итерируясь по списку, выводим их название на языке пользователя и код -->
                <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected {% endif %}>
                    {{ language.name_local }} - {{ language.code }}
                </option>
            {% endfor %}
        </select>
        <input type="submit" value="set">
</form>
<br>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

Новостной портал/news/templates/article_delete.html
{% extends 'flatpages/default.html' %}
{% load i18n %}
{% block content %}
<br>
<h1>{% trans 'Удаление статьи' %}</h1>
<br>
<form action="{% url 'set_language' %}" method="POST"> 
		{% csrf_token %} <!-- Не забываем по csrf_token для POST запросов -->
        <input type="hidden" name="next" value="{{ redirect_to }}">
        <select name="language" id="">
            {% get_available_languages as LANGUAGES %} <!-- получаем языки -->
            {% get_language_info_list for LANGUAGES as languages %} <!-- Помещаем их в список languages -->
            {% get_current_language as LANGUAGE_CODE %}
            {% for language in languages %} <!-- Итерируясь по списку, выводим их название на языке пользователя и код -->
                <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected {% endif %}>
                    {{ language.name_local }} - {{ language.code }}
                </option>
            {% endfor %}
        </select>
        <input type="submit" value="set">
</form>
<br>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>{% trans 'Удаляем статью' %} "{{ object.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

Новостной портал/news/templates/invalid_articles_edit.html
{% extends 'flatpages/default.html' %}
{% load i18n %}
{% load custom_filter %}
{% block title %}
Invalid
{% endblock title %}

{% block content %}
<br>
<h1 style="text-align:center">{% trans 'Вы пытаетесь редактировать/удалить новость на странице с редактированием/удалением статьи' %}</h1>
<br>
<form action="{% url 'set_language' %}" method="POST"> 
		{% csrf_token %} <!-- Не забываем по csrf_token для POST запросов -->
        <input type="hidden" name="next" value="{{ redirect_to }}">
        <select name="language" id="">
            {% get_available_languages as LANGUAGES %} <!-- получаем языки -->
            {% get_language_info_list for LANGUAGES as languages %} <!-- Помещаем их в список languages -->
            {% get_current_language as LANGUAGE_CODE %}
            {% for language in languages %} <!-- Итерируясь по списку, выводим их название на языке пользователя и код -->
                <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected {% endif %}>
                    {{ language.name_local }} - {{ language.code }}
                </option>
            {% endfor %}
        </select>
        <input type="submit" value="set">
</form>
{% endblock content %}

Новостной портал/news/templates/invalid_news_edit.html
{% extends 'flatpages/default.html' %}
{% load i18n %}
{% load custom_filter %}
{% block title %}
Invalid
{% endblock title %}

{% block content %}
<br>
<h1 style="text-align:center">{% trans 'Вы пытаетесь редактировать/удалить статью на странице с редактированием/удалением новости' %}</h1>
<br>
<form action="{% url 'set_language' %}" method="POST"> 
		{% csrf_token %} <!-- Не забываем по csrf_token для POST запросов -->
        <input type="hidden" name="next" value="{{ redirect_to }}">
        <select name="language" id="">
            {% get_available_languages as LANGUAGES %} <!-- получаем языки -->
            {% get_language_info_list for LANGUAGES as languages %} <!-- Помещаем их в список languages -->
            {% get_current_language as LANGUAGE_CODE %}
            {% for language in languages %} <!-- Итерируясь по списку, выводим их название на языке пользователя и код -->
                <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected {% endif %}>
                    {{ language.name_local }} - {{ language.code }}
                </option>
            {% endfor %}
        </select>
        <input type="submit" value="set">
</form>
{% endblock content %}

Новостной портал/news/templates/last news.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Добрый день!</h2> <br>
    Последние новости за неделю:
    <br>
<p>{{text}}<a href="{{link}}">Читать продолжение в источнике</a></p>
</body>
</html>

Новостной портал/news/templates/news.html
{% extends 'flatpages/default.html' %}
{% load i18n %}
{% load tz %} <!-- не забываем загрузить тег для работы с часовыми поясами -->
{% load custom_filter %}
{% block title %}
News
{% endblock title %}

{% block content %}
   <br>
   <h1>{% trans 'Все новости/статьи' %}</h1>
   <br>
   <form action="{% url 'set_language' %}" method="POST"> 
   {% csrf_token %} <!-- Не забываем по csrf_token для POST запросов -->
        <input type="hidden" name="next" value="{{ redirect_to }}">
        <select name="language" id="">
            {% get_available_languages as LANGUAGES %} <!-- получаем языки -->
            {% get_language_info_list for LANGUAGES as languages %} <!-- Помещаем их в список languages -->
            {% get_current_language as LANGUAGE_CODE %}
            {% for language in languages %} <!-- Итерируясь по списку, выводим их название на языке пользователя и код -->
                <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected {% endif %}>
                    {{ language.name_local }} - {{ language.code }}
                </option>
            {% endfor %}
        </select>
        <input type="submit" value="set">
    </form>
	<br>
	{% get_current_timezone as TIME_ZONE %}
    <form action="" method="POST">
        {% csrf_token %}
        <label for="timezone">{% trans 'Выберите свой часовой пояс' %}:</label>
        <select name="timezone">
            {% for tz in timezones %}
            <option value="{{ tz }}"{% if tz == TIME_ZONE %} selected{% endif %}>{{ tz }}</option>
            {% endfor %}
        </select>
        <input type="submit" value="Set">
    </form>
 
    {{ TIME_ZONE }}
    {{ current_time|timezone:TIME_ZONE }} <!-- Отображаем время в выбранном часовом поясе  -->
   <hr>
<p style="text-align:left">
    {% if perms.news_bd.add_post %}
    <a href="{% url 'news_create' %}">{% trans 'Добавить новость' %}</a>
	<br>
    {% endif %}
    {% if perms.news_bd.add_post %}
    <a href="{% url 'article_create' %}">{% trans 'Добавить статью' %}</a>
	<br>
    {% endif %}
	<a href="{% url 'post_search' %}">{% trans 'Найти новость' %}</a>
</p>
   {% if posts %}
          <table align="center" border = "1">
        <tr>
            <th>{% trans 'Заголовок' %}</th>
            <th>{% trans 'Дата публикации' %}</th>
            <th>{% trans 'Текст новости/статьи' %}</th>
            <th>{% trans 'Категория' %}</th>
        </tr>

       {% for post in posts %}
        <tr>
            <td>{{ post.title|censor }}</td>
            <td>{{ post.time_post }}</td>
            <td>{{ post.text|truncatewords:20|censor}}</td>
            <td>
                {% for category in post.category.all %}
                <a href = "{% url 'category_list' category.id %}">{{category}}</a>
                {% endfor %}
            </td>
            <td>
                {% if perms.news_bd.change_post and post.type_post == 'NE' %}
                <a href="{% url 'news_edit' pk=post.id %}">{% trans 'Изменить новость' %}</a>
                {% elif perms.news_bd.change_post and post.type_post == 'AR' %}
                    <a href="{% url 'article_edit' pk=post.id %}">{% trans 'Изменить статью' %}</a>
                {% endif %}
            </td>
             <td>
                {% if perms.news_bd.delete_post and post.type_post == 'NE' %}
                <a href="{% url 'news_delete' pk=post.id %}">{% trans 'Удалить новость' %}</a>
                {% elif perms.news_bd.delete_post and post.type_post == 'AR' %}
                    <a href="{% url 'article_delete' pk=post.id %}">{% trans 'Удалить статью' %}</a>
                {% endif %}
            </td>
        </tr>
            {% endfor %}
    </table>

   {% else %}
       <h2>{% trans 'Свежих новостей нет!!!' %}</h2>
   {% endif %}

    {% if page_obj.has_previous %}
        <a href ="?page=1">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
        <a href ="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

    {{ page_obj.number }}

    {% if page_obj.has_next %}
         <a href ="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
        {% if page_obj.next_page_number != paginator.num_pages %}
            ...
        <a href ="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
        {% endif %}
    {% endif %}

{% endblock content %}

Новостной портал/news/templates/news_create.html
{% extends 'flatpages/default.html' %}
{% load i18n %}
{% block content %}
<br>
<h1>{% trans 'Новость' %}</h1>
<br>
<form action="{% url 'set_language' %}" method="POST"> 
		{% csrf_token %} <!-- Не забываем по csrf_token для POST запросов -->
        <input type="hidden" name="next" value="{{ redirect_to }}">
        <select name="language" id="">
            {% get_available_languages as LANGUAGES %} <!-- получаем языки -->
            {% get_language_info_list for LANGUAGES as languages %} <!-- Помещаем их в список languages -->
            {% get_current_language as LANGUAGE_CODE %}
            {% for language in languages %} <!-- Итерируясь по списку, выводим их название на языке пользователя и код -->
                <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected {% endif %}>
                    {{ language.name_local }} - {{ language.code }}
                </option>
            {% endfor %}
        </select>
        <input type="submit" value="set">
</form>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

Новостной портал/news/templates/news_delete.html
{% extends 'flatpages/default.html' %}
{% load i18n %}
{% block content %}
<br>
<h1>Удаление новости</h1>
<br>
<form action="{% url 'set_language' %}" method="POST"> 
		{% csrf_token %} <!-- Не забываем по csrf_token для POST запросов -->
        <input type="hidden" name="next" value="{{ redirect_to }}">
        <select name="language" id="">
            {% get_available_languages as LANGUAGES %} <!-- получаем языки -->
            {% get_language_info_list for LANGUAGES as languages %} <!-- Помещаем их в список languages -->
            {% get_current_language as LANGUAGE_CODE %}
            {% for language in languages %} <!-- Итерируясь по списку, выводим их название на языке пользователя и код -->
                <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected {% endif %}>
                    {{ language.name_local }} - {{ language.code }}
                </option>
            {% endfor %}
        </select>
        <input type="submit" value="set">
</form>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>{% trans 'Удаляем новость' %} "{{ object.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

Новостной портал/news/templates/news_search.html
{% extends 'flatpages/default.html' %}
{% load i18n %}
{% load tz %}
{% load custom_filter %}
{% load custom_tags %}

{% block title %}
News
{% endblock title %}

{% block content %}
<br>
   <h1>{% trans 'Все новости/статьи' %}</h1>
<br>
   <form action="{% url 'set_language' %}" method="POST"> 
		{% csrf_token %} <!-- Не забываем по csrf_token для POST запросов -->
        <input type="hidden" name="next" value="{{ redirect_to }}">
        <select name="language" id="">
            {% get_available_languages as LANGUAGES %} <!-- получаем языки -->
            {% get_language_info_list for LANGUAGES as languages %} <!-- Помещаем их в список languages -->
            {% get_current_language as LANGUAGE_CODE %}
            {% for language in languages %} <!-- Итерируясь по списку, выводим их название на языке пользователя и код -->
                <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected {% endif %}>
                    {{ language.name_local }} - {{ language.code }}
                </option>
            {% endfor %}
        </select>
        <input type="submit" value="set">
</form>
<br>
	{% get_current_timezone as TIME_ZONE %}
    <form action="" method="POST">
        {% csrf_token %}
        <label for="timezone">{% trans 'Выберите свой часовой пояс' %}:</label>
        <select name="timezone">
            {% for tz in timezones %}
            <option value="{{ tz }}"{% if tz == TIME_ZONE %} selected{% endif %}>{{ tz }}</option>
            {% endfor %}
        </select>
        <input type="submit" value="Set">
    </form>
 
    {{ TIME_ZONE }}
    {{ current_time|timezone:TIME_ZONE }} <!-- Отображаем время в выбранном часовом поясе  -->
<hr>

   <form action="" method="get">
       {{ filterset.form.as_p }}
       <input type="submit" value="Найти" />
   </form>

    <br>
   {% if posts %}
          <table align="center" border = "1">
        <tr>
            <th>{% trans 'Заголовок' %}</th>
            <th>{% trans 'Дата публикации' %}</th>
            <th>{% trans 'Текст новости/статьи' %}</th>
			<th>{% trans 'Категория' %}</th>
        </tr>

        {% for post in posts %}
        <tr>
            <td>{{ post.title|censor }}</td>
            <td>{{ post.time_post }}</td>
            <td>{{ post.text|truncatewords:20|censor}}</td>
			<td>
                {% for category in post.category.all %}
                <a href = "{% url 'category_list' category.id %}">{{category}}</a>
                {% endfor %}
            </td>
            <td>
                {% if perms.news_bd.change_post and post.type_post == 'NE' %}
                <a href="{% url 'news_edit' pk=post.id %}">{% trans 'Изменить новость' %}</a>
                {% elif perms.news_bd.change_post and post.type_post == 'AR' %}
                    <a href="{% url 'article_edit' pk=post.id %}">{% trans 'Изменить статью' %}</a>
                {% endif %}
            </td>
             <td>
                {% if perms.news_bd.delete_post and post.type_post == 'NE' %}
                <a href="{% url 'news_delete' pk=post.id %}">{% trans 'Удалить новость' %}</a>
                {% elif perms.news_bd.delete_post and post.type_post == 'AR' %}
                    <a href="{% url 'article_delete' pk=post.id %}">{% trans 'Удалить статью' %}</a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>

   {% else %}
       <h2>{% trans 'Свежих новостей нет!!!' %}</h2>
   {% endif %}

    {% if page_obj.has_previous %}
        <a href ="?{% url_replace page=1 %}">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
        <a href ="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

    {{ page_obj.number }}

    {% if page_obj.has_next %}
         <a href ="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
        {% if page_obj.next_page_number != paginator.num_pages %}
            ...
        <a href ="?{% url_replace page=paginator.num_pages %}">{{ paginator.num_pages }}</a>
        {% endif %}
    {% endif %}

{% endblock content %}

Новостной портал/news/templates/post_created_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Добрый день! <br>
    Новая статья/новость в категории <a href = "{{link}}">"{{name_category}}"</a></h2>
<p>{{text}}</p>
</body>
</html>

Новостной портал/news/templates/subscribe.html
{% extends 'flatpages/default.html' %}

{% load custom_filter %}
{% block title %}
Subscribe
{% endblock title %}

{% block content %}
<h1 class="text-center">{{message}}"{{category}}"</h1>
{% endblock content %}

Новостной портал/news/templates/subscriptions.html
{% extends 'flatpages/default.html' %}
{% load i18n %}
{% load tz %}
{% load custom_filter %}
{% block title %}
Categories
{% endblock title %}

{% block content %}
<br>
   <h1>{% trans 'Все новости/статьи' %}</h1>
<br>
   <form action="{% url 'set_language' %}" method="POST"> 
		{% csrf_token %} <!-- Не забываем по csrf_token для POST запросов -->
        <input type="hidden" name="next" value="{{ redirect_to }}">
        <select name="language" id="">
            {% get_available_languages as LANGUAGES %} <!-- получаем языки -->
            {% get_language_info_list for LANGUAGES as languages %} <!-- Помещаем их в список languages -->
            {% get_current_language as LANGUAGE_CODE %}
            {% for language in languages %} <!-- Итерируясь по списку, выводим их название на языке пользователя и код -->
                <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected {% endif %}>
                    {{ language.name_local }} - {{ language.code }}
                </option>
            {% endfor %}
        </select>
        <input type="submit" value="set">
</form>
<br>
{% get_current_timezone as TIME_ZONE %}
    <form action="" method="POST">
        {% csrf_token %}
        <label for="timezone">{% trans 'Выберите свой часовой пояс' %}:</label>
        <select name="timezone">
            {% for tz in timezones %}
            <option value="{{ tz }}"{% if tz == TIME_ZONE %} selected{% endif %}>{{ tz }}</option>
            {% endfor %}
        </select>
        <input type="submit" value="Set">
    </form>
 
    {{ TIME_ZONE }}
    {{ current_time|timezone:TIME_ZONE }} <!-- Отображаем время в выбранном часовом поясе  -->
<br>
{% if is_not_subscriber %}
            <p><a href="{% url 'subscribe' category.id %}">{% trans 'Подписаться' %}</a></p>
{% endif %}
   <hr>
<p style="text-align:left">
    {% if perms.news_bd.add_post %}
    <a href="{% url 'news_create' %}">{% trans 'Добавить новость' %}</a>
    {% endif %}
    <br>
    {% if perms.news_bd.add_post %}
    <a href="{% url 'article_create' %}">{% trans 'Добавить статью' %}</a>
    {% endif %}
</p>
   {% if category_news_list %}
          <table align="center" border = "1">
        <tr>
            <th>{% trans 'Заголовок' %}</th>
            <th>{% trans 'Дата публикации' %}</th>
            <th>{% trans 'Текст новости/статьи' %}</th>
            <th>{% trans 'Категория' %}</th>
        </tr>

        {% for post in category_news_list %}
        <tr>
            <td>{{ post.title|censor }}</td>
            <td>{{ post.time_post }}</td>
            <td>{{ post.text|truncatewords:20|censor}}</td>
            <td>
                {% for category in post.category.all %}
                <a href = "{% url 'category_list' category.id %}">{{category}}</a>
               {% endfor %}
            </td>
            <td>
                {% if perms.news_bd.change_post and post.type_post == 'NE' %}
                <a href="{% url 'news_edit' pk=post.id %}">Изменить новость</a>
                {% elif perms.news_bd.change_post and post.type_post == 'AR' %}
                    <a href="{% url 'article_edit' pk=post.id %}">Изменить статью</a>
                {% endif %}
            </td>
             <td>
                {% if perms.news_bd.delete_post and post.type_post == 'NE' %}
                <a href="{% url 'news_delete' pk=post.id %}">Удалить новость</a>
                {% elif perms.news_bd.delete_post and post.type_post == 'AR' %}
                    <a href="{% url 'article_delete' pk=post.id %}">Удалить статью</a>
                {% endif %}
            </td>
        </tr>
              {% endfor %}
    </table>


   {% else %}
       <h2>{% trans 'Свежих новостей нет!!!' %}</h2>
   {% endif %}

    {% if page_obj.has_previous %}
        <a href ="?page=1">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
        <a href ="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

    {{ page_obj.number }}

    {% if page_obj.has_next %}
         <a href ="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
        {% if page_obj.next_page_number != paginator.num_pages %}
            ...
        <a href ="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
        {% endif %}
    {% endif %}

{% endblock content %}

Новостной портал/news/templates/successful_deleting.html
{% extends 'flatpages/default.html' %}
{% load i18n %}
{% block content %}
<br>
<h1>{% trans 'Новость/статья успешно удалена!' %}</h1>
<br>
<form action="{% url 'set_language' %}" method="POST">
		{% csrf_token %} <!-- Не забываем по csrf_token для POST запросов -->
        <input type="hidden" name="next" value="{{ redirect_to }}">
        <select name="language" id="">
            {% get_available_languages as LANGUAGES %} <!-- получаем языки -->
            {% get_language_info_list for LANGUAGES as languages %} <!-- Помещаем их в список languages -->
            {% get_current_language as LANGUAGE_CODE %}
            {% for language in languages %} <!-- Итерируясь по списку, выводим их название на языке пользователя и код -->
                <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected {% endif %}>
                    {{ language.name_local }} - {{ language.code }}
                </option>
            {% endfor %}
        </select>
        <input type="submit" value="set">
</form>
<hr>
<a style="font-align: center" href="{% url 'post_list' %}">{% trans 'Вернуться на главную страницу' %}</a>
{% endblock content %}

Новостной портал/news/templates/swagger-ui.html
<!DOCTYPE html>
<html>
 <head>
   <title>Swagger</title>
   <meta 
charset="utf-8"/>
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="stylesheet" type="text/css" href="//unpkg.com/swagger-ui-dist@3/swagger-ui.css" />
 </head>
 <body>
   <div id="swagger-ui"></div>
   <script src="//unpkg.com/swagger-ui-dist@3/swagger-ui-bundle.js"></script>
   <script>
   const ui = SwaggerUIBundle({
       url: "/static/openapi-schema.yml",
       dom_id: '#swagger-ui',
       presets: [
         SwaggerUIBundle.presets.apis,
         SwaggerUIBundle.SwaggerUIStandalonePreset
       ],
       layout: "BaseLayout",
       requestInterceptor: (request) => {
         request.headers['X-CSRFToken'] = "{{ csrf_token }}"
         return request;
       }
     })
   </script>
 </body>
</html>